# Generated by Django 5.1.7 on 2025-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='decrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='decrypted_files/'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='encrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_files/'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_decrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='stegano_image',
            field=models.ImageField(blank=True, null=True, upload_to='key_images/'),
        ),
    ]
